In [4]:
import numpy as np
import cv2

In [5]:
cap = cv2.VideoCapture('sample.mp4')


while cap.isOpened():
    
    sucess,frame = cap.read()
    if sucess:
        print("Sucess,We won this program")
        Gframe =cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
        
        zeros = np.zeros((300,300,3),np.float32)
     
        
        cv2.line(frame,(0,0),(520,590),(0,0,255),6)
        cv2.rectangle(frame,(0,0),(590,590),(0,255,0),12)
        cv2.putText(frame,"HI NEWLEARNER",(220,220),cv2.FONT_HERSHEY_SIMPLEX,1,(255,0,0),4)
       
        cv2.line(Gframe,(0,0),(520,590),(0,0,255),6)
        cv2.rectangle(Gframe,(0,0),(590,590),(0,255,0),12)
        cv2.putText(Gframe,"HI NEWLEARNER",(220,220),cv2.FONT_HERSHEY_SIMPLEX,1,(255,0,0),4)
        
        b,g,r = cv2.split(frame)
        print("Blue channel: ", b)
        print("Green channel: ", g)
        print("Red channel: ", r)
        
        cv2.imshow('frame',frame)
        cv2.imshow('Gframe',Gframe)
        
       

        k=cv2.waitKey(0)
        if k & 0xff == ord('q'):
            break
    else:
        print("ITs not working")
        break

cap.release()
cv2.destroyAllWindows()
        

Sucess,We won this program
Blue channel:  [[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [202 202 202 ... 182 182 182]
 [202 202 202 ... 182 182 182]
 [202 202 202 ... 182 182 182]]
Green channel:  [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [202 202 202 ... 182 182 182]
 [202 202 202 ... 182 182 182]
 [202 202 202 ... 182 182 182]]
Red channel:  [[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [193 193 193 ... 180 180 180]
 [193 193 193 ... 180 180 180]
 [193 193 193 ... 180 180 180]]
